Repository novoda/merlin, pull requests merged in 2018-11, with the labels that each got.

#180 Update README.md
  README.md
Labels: housekeeping

#182 MER-174 Remove releases folder
  releases/merlin-core-v0.2.jar
  releases/merlin-core-v0.4.1.jar
  releases/merlin-core-v0.5.aar
  releases/res/on_connect.jpg
  releases/res/on_disconnect.jpg
Labels: discussion, housekeeping

#183 MER-168 concurrent modification exception
  core/src/main/java/com/novoda/merlin/Register.java
  core/src/test/java/com/novoda/merlin/ConnectCallbackManagerTest.java
Labels: bug

#184 Disconnect when Http connection errors
  build.gradle
  core/src/main/java/com/novoda/merlin/HttpRequestMaker.java
Labels: bug
